In [ ]:
import sys

print("Python executable:")
print(sys.executable)

print("\nPython version:")
print(sys.version)

In [2]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

print("Project root:")
print(PROJECT_ROOT)

print("\nProcessed data:")
for file in (PROJECT_ROOT / "data" / "processed").iterdir():
    print(" -", file.name)

print("\nResults:")
for file in (PROJECT_ROOT / "results").iterdir():
    print(" -", file.name)

Project root:
c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)

Processed data:
 - evaluation_pairs.csv
 - nlp_resume_job_pairs.csv
 - resumes_clean.csv
 - resume_job_pairs_clean.csv

Results:
 - hybrid_matching_results.csv
 - jd_embeddings.npy
 - resume_embeddings.npy
 - semantic_results.csv
 - tfidf_test_results.csv
 - tfidf_train_results.csv
 - tfidf_validation_results.csv
 - tfidf_vocabulary.csv
 - tfidf_vs_semantic_comparison.csv

In [3]:
import os
import re
import json
import numpy as np
import pandas as pd

from pathlib import Path

print("Basic libraries imported successfully.")

Basic libraries imported successfully.

In [4]:
from pathlib import Path

# Notebook is inside: project/notebooks/
PROJECT_ROOT = Path.cwd().parent

DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
RESULTS_DIR = PROJECT_ROOT / "results"

print("Project root:")
print(PROJECT_ROOT)

print("\nProject folders:")
print("Raw data:", DATA_RAW)
print("Processed data:", DATA_PROCESSED)
print("Results:", RESULTS_DIR)

Project root:
c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)

Project folders:
Raw data: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\data\raw
Processed data: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\data\processed
Results: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\results

In [5]:
print("PROCESSED DATA FILES")
print("=" * 50)

for file in sorted(DATA_PROCESSED.iterdir()):
    print(file.name)

print("\nRESULT FILES")
print("=" * 50)

for file in sorted(RESULTS_DIR.iterdir()):
    print(file.name)

PROCESSED DATA FILES
==================================================
evaluation_pairs.csv
nlp_resume_job_pairs.csv
resume_job_pairs_clean.csv
resumes_clean.csv

RESULT FILES
==================================================
hybrid_matching_results.csv
jd_embeddings.npy
resume_embeddings.npy
semantic_results.csv
tfidf_test_results.csv
tfidf_train_results.csv
tfidf_validation_results.csv
tfidf_vocabulary.csv
tfidf_vs_semantic_comparison.csv

In [6]:
print("PROCESSED DATA FILES")
print("=" * 50)

for file in sorted(DATA_PROCESSED.iterdir()):
    print(file.name)

print("\nRESULT FILES")
print("=" * 50)

for file in sorted(RESULTS_DIR.iterdir()):
    print(file.name)

PROCESSED DATA FILES
==================================================
evaluation_pairs.csv
nlp_resume_job_pairs.csv
resume_job_pairs_clean.csv
resumes_clean.csv

RESULT FILES
==================================================
hybrid_matching_results.csv
jd_embeddings.npy
resume_embeddings.npy
semantic_results.csv
tfidf_test_results.csv
tfidf_train_results.csv
tfidf_validation_results.csv
tfidf_vocabulary.csv
tfidf_vs_semantic_comparison.csv

Load Existing Hybrid Results

In [7]:
hybrid_path = RESULTS_DIR / "hybrid_matching_results.csv"

hybrid_df = pd.read_csv(hybrid_path)

print("Hybrid results shape:", hybrid_df.shape)

print("\nColumns:")
print(hybrid_df.columns.tolist())

display(hybrid_df.head(3))

Hybrid results shape: (10174, 21)

Columns:
['pair_id', 'role', 'resume_text', 'job_description', 'semantic_score', 'tfidf_score', 'resume_skills', 'jd_skills', 'matching_skills', 'missing_skills', 'skill_score', 'tfidf_normalized', 'semantic_normalized', 'skill_normalized', 'skill_available', 'hybrid_score', 'hybrid_score_100', 'tfidf_contribution', 'semantic_contribution', 'skill_contribution', 'match_category']

,pair_id,role,resume_text,job_description,semantic_score,tfidf_score,resume_skills,jd_skills,matching_skills,missing_skills,...,tfidf_normalized,semantic_normalized,skill_normalized,skill_available,hybrid_score,hybrid_score_100,tfidf_contribution,semantic_contribution,skill_contribution,match_category
0,P00001,E-commerce Specialist,Here's a professional resume for Jason Jones: ...,Be part of a passionate team at the forefront ...,52.388668,5.026669,"['customer service', 'data analysis', 'e-comme...","['e-commerce', 'machine learning']",['e-commerce'],['machine learning'],...,0.177484,0.601913,0.5,1,0.454202,45.420161,0.053245,0.300956,0.1,Moderate
1,P00002,Game Developer,Here's a professional resume for Ann Marshall:...,Help us build the next-generation products as ...,33.770626,7.068954,"['c', 'github']",[],[],[],...,0.249594,0.351423,NaN,0,0.313237,31.323689,0.074878,0.175711,0.0,Low
2,P00003,Human Resources Specialist,Here's a professional resume for Patrick Mccla...,We need a Human Resources Specialist to enhanc...,69.238910,8.389403,"['data analysis', 'employee relations', 'human...",['human resources'],['human resources'],[],...,0.296217,0.828619,1.0,1,0.703174,70.317446,0.088865,0.414309,0.2,Strong

Inspect Hybrid Score

In [8]:
print(hybrid_df["hybrid_score_100"].describe())

count    10174.000000
mean        45.747603
std         15.485814
min          1.811250
25%         35.427918
50%         46.190828
75%         57.421522
max         88.785979
Name: hybrid_score_100, dtype: float64

In [10]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
RESULTS_DIR = PROJECT_ROOT / "results"

print("Project root:", PROJECT_ROOT)
print("Processed data:", DATA_PROCESSED)
print("Results:", RESULTS_DIR)

Project root: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)
Processed data: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\data\processed
Results: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\results

In [11]:
import pandas as pd

pairs_path = DATA_PROCESSED / "resume_job_pairs_clean.csv"

pairs_df = pd.read_csv(pairs_path)

print("Pairs dataframe shape:", pairs_df.shape)
print("Columns:")
print(pairs_df.columns.tolist())

Pairs dataframe shape: (10174, 10)
Columns:
['pair_id', 'original_id', 'candidate_name', 'role', 'resume_text', 'job_description', 'decision', 'decision_reason', 'resume_normalized', 'jd_normalized']

In [12]:
hybrid_path = RESULTS_DIR / "hybrid_matching_results.csv"

hybrid_df = pd.read_csv(hybrid_path)

print("Hybrid dataframe shape:", hybrid_df.shape)
print("Columns:")
print(hybrid_df.columns.tolist())

Hybrid dataframe shape: (10174, 21)
Columns:
['pair_id', 'role', 'resume_text', 'job_description', 'semantic_score', 'tfidf_score', 'resume_skills', 'jd_skills', 'matching_skills', 'missing_skills', 'skill_score', 'tfidf_normalized', 'semantic_normalized', 'skill_normalized', 'skill_available', 'hybrid_score', 'hybrid_score_100', 'tfidf_contribution', 'semantic_contribution', 'skill_contribution', 'match_category']

Check the pair ID

In [13]:
print("Pairs:")
print(pairs_df["pair_id"].head())

print("\nHybrid:")
print(hybrid_df["pair_id"].head())

Pairs:
0    P00001
1    P00002
2    P00003
3    P00004
4    P00005
Name: pair_id, dtype: str

Hybrid:
0    P00001
1    P00002
2    P00003
3    P00004
4    P00005
Name: pair_id, dtype: str

In [ ]:
Merge existing information

In [33]:
analysis_df = hybrid_df.copy()

print("Analysis dataframe shape:", analysis_df.shape)

display(analysis_df.head(3))

Analysis dataframe shape: (10174, 21)

,pair_id,role,resume_text,job_description,semantic_score,tfidf_score,resume_skills,jd_skills,matching_skills,missing_skills,...,tfidf_normalized,semantic_normalized,skill_normalized,skill_available,hybrid_score,hybrid_score_100,tfidf_contribution,semantic_contribution,skill_contribution,match_category
0,P00001,E-commerce Specialist,Here's a professional resume for Jason Jones: ...,Be part of a passionate team at the forefront ...,52.388668,5.026669,"['customer service', 'data analysis', 'e-comme...","['e-commerce', 'machine learning']",['e-commerce'],['machine learning'],...,0.177484,0.601913,0.5,1,0.454202,45.420161,0.053245,0.300956,0.1,Moderate
1,P00002,Game Developer,Here's a professional resume for Ann Marshall:...,Help us build the next-generation products as ...,33.770626,7.068954,"['c', 'github']",[],[],[],...,0.249594,0.351423,NaN,0,0.313237,31.323689,0.074878,0.175711,0.0,Low
2,P00003,Human Resources Specialist,Here's a professional resume for Patrick Mccla...,We need a Human Resources Specialist to enhanc...,69.238910,8.389403,"['data analysis', 'employee relations', 'human...",['human resources'],['human resources'],[],...,0.296217,0.828619,1.0,1,0.703174,70.317446,0.088865,0.414309,0.2,Strong

In [34]:
skill_columns = [
    "resume_skills",
    "jd_skills",
    "matching_skills",
    "missing_skills",
    "skill_score"
]

print("Skill columns:")

for column in skill_columns:
    print(column, "->", column in analysis_df.columns)

Skill columns:
resume_skills -> True
jd_skills -> True
matching_skills -> True
missing_skills -> True
skill_score -> True

Check missing hybrid scores

In [35]:
print(
    "Missing hybrid scores:",
    analysis_df["hybrid_score_100"].isna().sum()
)

Missing hybrid scores: 0

Create a function for resume text cleaning

In [16]:
def clean_text(text):
    if pd.isna(text):
        return ""
    
    text = str(text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


analysis_df["resume_text"] = analysis_df["resume_text"].apply(clean_text)
analysis_df["job_description"] = analysis_df["job_description"].apply(clean_text)

print("Text cleaning completed.")

Text cleaning completed.

Inspect one resume and JD

In [17]:
sample = analysis_df.iloc[0]

print("PAIR ID:")
print(sample["pair_id"])

print("\nRESUME:")
print(sample["resume_text"][:2000])

print("\nJOB DESCRIPTION:")
print(sample["job_description"][:2000])

PAIR ID:
P00001

RESUME:
Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies. Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20% * Created and executed online advertising campaigns that generated a 50% increase in sales and a 20% increase in conversion rates * Analyzed website analytics to identify trends, optimize user experience, and improve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytics to identify trends and areas for improvement Education: * Bachelor's Degree in Business Administration, [University Name] (2015) Skills: * Inventory Management * SEO for E-commerce * Online Advertising (Google Ads, Facebook Ads) * Analytics (Google Analytics, Excel) * Data Analysis * E-commerce Pl

JOB DESCRIPTION:
Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future.

PDF/DOCX extraction imports

In [18]:
import pymupdf
from docx import Document

print("Document extraction libraries imported successfully.")

Document extraction libraries imported successfully.

PDF extraction function

In [19]:
def extract_text_from_pdf(file_path):
    """
    Extract text from a PDF file.
    """
    document = pymupdf.open(file_path)

    pages = []

    for page in document:
        pages.append(page.get_text())

    document.close()

    return "\n".join(pages).strip()

DOCX extraction function

In [20]:
def extract_text_from_docx(file_path):
    """
    Extract text from a DOCX file.
    """
    document = Document(file_path)

    paragraphs = [
        paragraph.text
        for paragraph in document.paragraphs
        if paragraph.text.strip()
    ]

    return "\n".join(paragraphs).strip()

Generic document extractor

In [21]:
def extract_document_text(file_path):
    """
    Extract text from PDF or DOCX.
    """
    file_path = Path(file_path)

    suffix = file_path.suffix.lower()

    if suffix == ".pdf":
        return extract_text_from_pdf(file_path)

    elif suffix == ".docx":
        return extract_text_from_docx(file_path)

    else:
        raise ValueError(
            f"Unsupported file type: {suffix}. "
            "Use PDF or DOCX."
        )

Test extraction function

In [22]:
print("Document extraction functions are ready.")

Document extraction functions are ready.

Resume section extraction

In [23]:
SECTION_PATTERNS = {
    "summary": [
        "summary",
        "professional summary",
        "profile",
        "objective",
        "career objective"
    ],
    "skills": [
        "skills",
        "technical skills",
        "core skills",
        "key skills"
    ],
    "experience": [
        "experience",
        "work experience",
        "professional experience",
        "employment"
    ],
    "education": [
        "education",
        "academic background",
        "qualifications"
    ],
    "projects": [
        "projects",
        "academic projects",
        "personal projects"
    ],
    "certifications": [
        "certifications",
        "certificates",
        "courses"
    ]
}

print("Section patterns created.")

Section patterns created.

Section detection helper

In [24]:
def detect_section_heading(line):
    """
    Detect whether a line looks like a resume section heading.
    """
    normalized = re.sub(r"[^a-zA-Z ]", "", line.lower()).strip()

    for section, headings in SECTION_PATTERNS.items():
        if normalized in headings:
            return section

    return None

Resume section parser

In [25]:
def extract_resume_sections(text):
    """
    Split resume text into basic sections.
    """
    lines = text.splitlines()

    sections = {}
    current_section = "general"

    sections[current_section] = []

    for line in lines:
        line = line.strip()

        if not line:
            continue

        detected = detect_section_heading(line)

        if detected:
            current_section = detected

            if current_section not in sections:
                sections[current_section] = []

        else:
            sections.setdefault(current_section, [])
            sections[current_section].append(line)

    # Convert lists to strings
    sections = {
        section: "\n".join(content).strip()
        for section, content in sections.items()
    }

    return sections

Test resume section extraction

In [26]:
sample_resume = analysis_df.iloc[0]["resume_text"]

resume_sections = extract_resume_sections(sample_resume)

for section, content in resume_sections.items():
    print(f"\n--- {section.upper()} ---")
    print(content[:500])

--- GENERAL ---
Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex d

JD section extraction

In [27]:
JD_SECTION_PATTERNS = {
    "responsibilities": [
        "responsibilities",
        "key responsibilities",
        "roles and responsibilities",
        "what you will do"
    ],
    "requirements": [
        "requirements",
        "qualifications",
        "required qualifications",
        "basic qualifications"
    ],
    "skills": [
        "skills",
        "technical skills",
        "required skills",
        "preferred skills"
    ],
    "experience": [
        "experience",
        "required experience",
        "preferred experience"
    ],
    "education": [
        "education",
        "educational qualification",
        "qualifications"
    ]
}

print("JD section patterns created.")

JD section patterns created.

JD heading detector

In [28]:
def detect_jd_section_heading(line):
    normalized = re.sub(r"[^a-zA-Z ]", "", line.lower()).strip()

    for section, headings in JD_SECTION_PATTERNS.items():
        if normalized in headings:
            return section

    return None

JD parser

In [29]:
def extract_jd_sections(text):
    lines = text.splitlines()

    sections = {}
    current_section = "general"

    sections[current_section] = []

    for line in lines:
        line = line.strip()

        if not line:
            continue

        detected = detect_jd_section_heading(line)

        if detected:
            current_section = detected

            if current_section not in sections:
                sections[current_section] = []

        else:
            sections.setdefault(current_section, [])
            sections[current_section].append(line)

    sections = {
        section: "\n".join(content).strip()
        for section, content in sections.items()
    }

    return sections

Test JD extraction

In [30]:
sample_jd = analysis_df.iloc[0]["job_description"]

jd_sections = extract_jd_sections(sample_jd)

for section, content in jd_sections.items():
    print(f"\n--- {section.upper()} ---")
    print(content[:500])

--- GENERAL ---
Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future.

Build an explainable analysis object

In [36]:
def build_matching_summary(row):
    return {
        "pair_id": row["pair_id"],
        "role": row.get("role", ""),
        "tfidf_score": row.get("tfidf_score", None),
        "semantic_score": row.get("semantic_score", None),
        "hybrid_score": row.get("hybrid_score_100", None),
        "resume": row["resume_text"],
        "job_description": row["job_description"]
    }

Test the summary

In [37]:
sample_summary = build_matching_summary(analysis_df.iloc[0])

for key, value in sample_summary.items():
    if key in ["resume", "job_description"]:
        print(f"{key}: {str(value)[:300]}...")
    else:
        print(f"{key}: {value}")

pair_id: P00001
role: E-commerce Specialist
tfidf_score: 5.02666936625147
semantic_score: 52.388668
hybrid_score: 45.42016134915499
resume: Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in ...
job_description: Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future....

Environment variables

In [40]:
from pathlib import Path

print("Current working directory:")
print(Path.cwd())

print("\nProject root:")
print(PROJECT_ROOT)

print("\nDoes .env exist?")
print((PROJECT_ROOT / ".env").exists())

print("\n.env path:")
print(PROJECT_ROOT / ".env")

Current working directory:
c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\notebooks

Project root:
c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)

Does .env exist?
True

.env path:
c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\.env

In [1]:
# Cell 27 — Test local Ollama connection

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "qwen2.5:3b"

payload = {
    "model": MODEL_NAME,
    "prompt": "Explain in one sentence what a job description is.",
    "stream": False
}

response = requests.post(
    OLLAMA_URL,
    json=payload,
    timeout=120
)

response.raise_for_status()

result = response.json()

print(result["response"])

A job description is a document that outlines the key responsibilities, qualifications, and requirements of a job position.

In [5]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent

RESULTS_DIR = PROJECT_ROOT / "results"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

print("Project root:", PROJECT_ROOT)
print("Results directory:", RESULTS_DIR)
print("Results directory exists:", RESULTS_DIR.exists())

Project root: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)
Results directory: c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\results
Results directory exists: True

In [6]:
# Restore analysis dataframe

import pandas as pd

HYBRID_RESULTS = RESULTS_DIR / "hybrid_matching_results.csv"

hybrid_df = pd.read_csv(HYBRID_RESULTS)

analysis_df = hybrid_df.copy()

print("analysis_df restored successfully")
print("Shape:", analysis_df.shape)

analysis_df restored successfully
Shape: (10174, 21)

In [7]:
print("analysis_df exists:", "analysis_df" in globals())

if "analysis_df" in globals():
    print("Shape:", analysis_df.shape)

analysis_df exists: True
Shape: (10174, 21)

In [8]:
# Cell 28 — Inspect resume and job description text

sample = analysis_df.iloc[0]

print("PAIR ID:")
print(sample["pair_id"])

print("\nROLE:")
print(sample["role"])

print("\nRESUME:")
print(sample["resume_text"][:2000])

print("\nJOB DESCRIPTION:")
print(sample["job_description"][:2000])

PAIR ID:
P00001

ROLE:
E-commerce Specialist

RESUME:
Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies. Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20% * Created and executed online advertising campaigns that generated a 50% increase in sales and a 20% increase in conversion rates * Analyzed website analytics to identify trends, optimize user experience, and improve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytics to identify trends and areas for improvement Education: * Bachelor's Degree in Business Administration, [University Name] (2015) Skills: * Inventory Management * SEO for E-commerce * Online Advertising (Google Ads, Facebook Ads) * Analytics (Google Analytics, Excel) * Data Analysis * E-commerce Pl

JOB DESCRIPTION:
Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future.

In [9]:
# Cell 29 — Inspect resume and job description

sample = analysis_df.iloc[0]

print("PAIR ID:")
print(sample["pair_id"])

print("\nROLE:")
print(sample["role"])

print("\nRESUME:")
print(sample["resume_text"][:2000])

print("\nJOB DESCRIPTION:")
print(sample["job_description"][:2000])

PAIR ID:
P00001

ROLE:
E-commerce Specialist

RESUME:
Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies. Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20% * Created and executed online advertising campaigns that generated a 50% increase in sales and a 20% increase in conversion rates * Analyzed website analytics to identify trends, optimize user experience, and improve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytics to identify trends and areas for improvement Education: * Bachelor's Degree in Business Administration, [University Name] (2015) Skills: * Inventory Management * SEO for E-commerce * Online Advertising (Google Ads, Facebook Ads) * Analytics (Google Analytics, Excel) * Data Analysis * E-commerce Pl

JOB DESCRIPTION:
Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future.

In [10]:
# Cell 30 — Check job description

jd_text = sample["job_description"]

print("Job Description length:", len(jd_text))

print("\nJOB DESCRIPTION PREVIEW:\n")
print(jd_text[:3000])

Job Description length: 137

JOB DESCRIPTION PREVIEW:

Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future.

In [11]:
# Cell 31 — Print complete job description

print(repr(sample["job_description"]))

'Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future.'

In [29]:
# Cell 32 — Sentence-aware document chunking function

import re

def chunk_text(text, chunk_size=500, overlap=100):
    """
    Split text into chunks while trying to preserve complete sentences.

    Short texts are kept as a single chunk.
    Longer texts are grouped into chunks close to the target size.
    """

    text = str(text).strip()

    if not text:
        return []

    # Keep short documents as one chunk
    if len(text) <= chunk_size:
        return [text]

    # Split text into sentences while preserving sentence-ending punctuation
    sentences = re.split(r'(?<=[.!?])\s+', text)

    chunks = []
    current_chunk = ""

    for sentence in sentences:

        sentence = sentence.strip()

        if not sentence:
            continue

        # If adding the sentence stays within the target size
        if len(current_chunk) + len(sentence) + 1 <= chunk_size:
            current_chunk += (" " if current_chunk else "") + sentence

        else:
            # Save the current chunk
            if current_chunk:
                chunks.append(current_chunk.strip())

            # Start a new chunk with the current sentence
            current_chunk = sentence

    # Add the final chunk
    if current_chunk:
        chunks.append(current_chunk.strip())

    return chunks

In [32]:
# Cell 33A — Test improved chunking on the current resume text

original_resume_text = "\n".join(resume_chunks)

test_chunks = chunk_text(original_resume_text)

print("Original reconstructed text length:", len(original_resume_text))
print("New number of chunks:", len(test_chunks))

for i, chunk in enumerate(test_chunks, start=1):
    print(f"\n--- New Chunk {i} ---")
    print(chunk)

Original reconstructed text length: 3201
New number of chunks: 3

--- New Chunk 1 ---
Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels.

--- New Chunk 2 ---
Skilled in analyzing complex d
ne sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies.

--- New Chunk 3 ---
Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strate
5% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20% * Created and executed online advertising campaigns that generated a 50% increase in sales and a 20% increase in conversion rates * Analyzed website analytics to identify trends, optimize user experience, and improve customer engagement * Collaborated with cross-functional teams to launch new product lines, promo
ve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytic
uting online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytics to identify trends and areas for improvement Education: * Bachelor's Degree in Business Administration, [University Name] (2015) Skills: * Inventory Management * SEO for E-commerce * Online Advertising (Google Ads, Facebook Ads) * Analytics (Google Analytics, Excel) * Data Analysis * E-commerce Platforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "I
atforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "Innovator of the Year" award for developing and implementing a data-driven approach to inventory management * Featured speaker at the "E-commerce Summit" conference, presenting on "Optimizing Inventory Levels for E-commerce Success" * Developed and implemented a social media strategy that increased followers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot I
ollowers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot Inbound Marketing Certification * Shopify Plus Certification References: Available upon request.

In [34]:
# Cell 33B — Find available DataFrames

import pandas as pd

dataframe_variables = []

for name, value in list(globals().items()):
    if isinstance(value, pd.DataFrame):
        dataframe_variables.append(name)

print("Available DataFrames:")

for name in dataframe_variables:
    print("-", name)

Available DataFrames:
- hybrid_df
- analysis_df

In [35]:
# Cell 33C — Check resume-related columns in analysis_df

resume_columns = [
    column for column in analysis_df.columns
    if "resume" in column.lower()
]

print("Resume-related columns:")
for column in resume_columns:
    print("-", column)

Resume-related columns:
- resume_text
- resume_skills

In [36]:
# Cell 33D — Create clean sentence-aware resume chunks

# Use the original resume text from analysis_df
original_resume_text = str(analysis_df["resume_text"].iloc[0]).strip()

# Create new sentence-aware chunks
clean_resume_chunks = chunk_text(
    original_resume_text,
    chunk_size=500,
    overlap=100
)

print("Original resume length:", len(original_resume_text))
print("Number of clean chunks:", len(clean_resume_chunks))

for i, chunk in enumerate(clean_resume_chunks, start=1):
    print(f"\n--- Clean Chunk {i} ---")
    print(chunk)

Original resume length: 2595
Number of clean chunks: 3

--- Clean Chunk 1 ---
Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels.

--- Clean Chunk 2 ---
Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies.

--- Clean Chunk 3 ---
Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20% * Created and executed online advertising campaigns that generated a 50% increase in sales and a 20% increase in conversion rates * Analyzed website analytics to identify trends, optimize user experience, and improve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytics to identify trends and areas for improvement Education: * Bachelor's Degree in Business Administration, [University Name] (2015) Skills: * Inventory Management * SEO for E-commerce * Online Advertising (Google Ads, Facebook Ads) * Analytics (Google Analytics, Excel) * Data Analysis * E-commerce Platforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "Innovator of the Year" award for developing and implementing a data-driven approach to inventory management * Featured speaker at the "E-commerce Summit" conference, presenting on "Optimizing Inventory Levels for E-commerce Success" * Developed and implemented a social media strategy that increased followers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot Inbound Marketing Certification * Shopify Plus Certification References: Available upon request.

In [37]:
# Cell 34A — Use the clean resume chunks

resume_chunks = clean_resume_chunks

print("Clean resume chunks are now active.")
print("Number of resume chunks:", len(resume_chunks))

for i, chunk in enumerate(resume_chunks, start=1):
    print(f"Chunk {i}: {len(chunk)} characters")

Clean resume chunks are now active.
Number of resume chunks: 3
Chunk 1: 469 characters
Chunk 2: 181 characters
Chunk 3: 1943 characters

In [38]:
# Cell 34B — Create embeddings for clean resume chunks

resume_embeddings = embedding_model.encode(
    resume_chunks,
    normalize_embeddings=True,
    convert_to_numpy=True
)

print("New resume embeddings created successfully.")
print("Resume embeddings shape:", resume_embeddings.shape)

New resume embeddings created successfully.
Resume embeddings shape: (3, 384)

In [39]:
# Cell 34C — Rebuild FAISS index with clean embeddings

import faiss

embedding_dimension = resume_embeddings.shape[1]

resume_index = faiss.IndexFlatIP(embedding_dimension)

resume_index.add(
    resume_embeddings.astype("float32")
)

print("FAISS index rebuilt successfully.")
print("Embedding dimension:", embedding_dimension)
print("Number of resume chunks in index:", resume_index.ntotal)

FAISS index rebuilt successfully.
Embedding dimension: 384
Number of resume chunks in index: 3

In [40]:
# Cell 35A — Retrieve relevant clean resume chunks

top_k = min(3, len(resume_chunks))

similarities, indices = resume_index.search(
    jd_embeddings.astype("float32"),
    top_k
)

print("Top matching clean resume chunks:\n")

for rank, (score, index) in enumerate(
    zip(similarities[0], indices[0]),
    start=1
):
    print(f"Rank {rank}")
    print(f"Similarity score: {score:.4f}")
    print(f"Resume chunk index: {index}")
    print(f"Text: {resume_chunks[index]}")
    print("-" * 80)

Top matching clean resume chunks:

Rank 1
Similarity score: 0.6150
Resume chunk index: 1
Text: Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies.
--------------------------------------------------------------------------------
Rank 2
Similarity score: 0.4913
Resume chunk index: 2
Text: Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20% * Created and executed online advertising campaigns that generated a 50% increase in sales and a 20% increase in conversion rates * Analyzed website analytics to identify trends, optimize user experience, and improve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytics to identify trends and areas for improvement Education: * Bachelor's Degree in Business Administration, [University Name] (2015) Skills: * Inventory Management * SEO for E-commerce * Online Advertising (Google Ads, Facebook Ads) * Analytics (Google Analytics, Excel) * Data Analysis * E-commerce Platforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "Innovator of the Year" award for developing and implementing a data-driven approach to inventory management * Featured speaker at the "E-commerce Summit" conference, presenting on "Optimizing Inventory Levels for E-commerce Success" * Developed and implemented a social media strategy that increased followers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot Inbound Marketing Certification * Shopify Plus Certification References: Available upon request.
--------------------------------------------------------------------------------
Rank 3
Similarity score: 0.4030
Resume chunk index: 0
Text: Here's a professional resume for Jason Jones: Jason Jones E-commerce Specialist Contact Information: * Email: [jasonjones@email.com](mailto:jasonjones@email.com) * Phone: 555-123-4567 * LinkedIn: linkedin.com/in/jasonjones Summary: Results-driven E-commerce Specialist with 5+ years of experience in inventory management, SEO, online advertising, and analytics. Proven track record of increasing online sales, improving website traffic, and optimizing inventory levels.
--------------------------------------------------------------------------------

In [41]:
# Cell 36A — Build retrieved context from the clean FAISS results

retrieved_chunks = [
    resume_chunks[index]
    for index in indices[0]
]

retrieved_context = "\n\n".join(retrieved_chunks)

print("New retrieved context created successfully.")
print("Number of retrieved chunks:", len(retrieved_chunks))
print("Retrieved context length:", len(retrieved_context), "characters")

New retrieved context created successfully.
Number of retrieved chunks: 3
Retrieved context length: 2597 characters

In [42]:
# Cell 37A — Create grounded RAG prompt using clean retrieved context

grounded_rag_prompt = f"""
You are an AI Resume and Job Matching Assistant.

Analyze the candidate's resume information against the job description.

IMPORTANT RULES:
1. Use ONLY information explicitly present in the provided resume context.
2. Do NOT invent or assume skills, qualifications, experience,
   technologies, employers, dates, or achievements.
3. If a requirement is not explicitly found in the resume context,
   state: "Not found in the retrieved resume information."
4. Do NOT treat general terms such as "data-driven", "analytical",
   or "optimization" as evidence of a specific technical skill
   unless that skill is explicitly stated.
5. Clearly distinguish between demonstrated skills and missing skills.
6. Keep the analysis factual and evidence-based.

JOB DESCRIPTION:
{jd_text}

RETRIEVED RESUME INFORMATION:
{retrieved_context}

Provide the analysis using these sections:

1. Overall Match
2. Matching Skills
3. Missing or Not-Found Skills
4. Relevant Experience
5. Education Alignment
6. Recommendations

For recommendations, only identify improvements that are supported
by the requirements in the job description and the gaps found in the
retrieved resume information.
"""

print("Clean grounded RAG prompt created successfully.")
print("Prompt length:", len(grounded_rag_prompt), "characters")

Clean grounded RAG prompt created successfully.
Prompt length: 3879 characters

In [43]:
# Cell 38A — Generate improved grounded RAG analysis

import requests

response = requests.post(
    "http://localhost:11434/api/generate",
    json={
        "model": "qwen2.5:3b",
        "prompt": grounded_rag_prompt,
        "stream": False
    },
    timeout=180
)

response.raise_for_status()

grounded_result = response.json()

grounded_analysis = grounded_result["response"]

print("Improved grounded AI analysis generated successfully.")
print("\n" + grounded_analysis)

Improved grounded AI analysis generated successfully.

### Analysis of the Resume Against the Job Description

#### 1. Overall Match
The candidate has relevant experience and skills that align well with the job requirements of a E-commerce Specialist at the forefront of machine learning. The candidate has a strong history of achieving results through various areas of expertise such as inventory management, SEO, online advertising, and data analysis. The candidate's experience at XYZ Corporation, where they managed multiple channels, developed and executed campaigns, and analyzed website analytics, is particularly relevant.

#### 2. Matching Skills
- **Inventory Management:** Demonstrated through "Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking."
- **SEO for E-commerce:** Demonstrated through "Developed and implemented SEO strategies that increased website traffic by 30% and improved search engine rankings by 20%."
- **Online Advertising:** Demonstrated through "Created and executed online advertising campaigns that generated a 50% increase in sales and a 20% increase in conversion rates."
- **Analytics:** Demonstrated through "Analyzed website analytics to identify trends, optimize user experience, and improve customer engagement."
- **Data Analysis:** Demonstrated through the various tasks listed, especially the development of data-driven approaches to inventory management.
- **E-commerce Platforms:** Demonstrated through experience with platforms such as Shopify and WooCommerce.
- **Customer Service:** While not explicitly mentioned, customer service skills are implied through tasks such as "resolving customer inquiries" and "assisted in managing inventory levels."

#### 3. Missing or Not-Found Skills
- **Machine Learning:** Not found in the retrieved resume information.
- **Analytical:** While implied in various tasks, such as data analysis and trend identification, the job description specifically mentions "machine learning," which is not covered in the resume.
- **E-commerce Trends:** The resume mentions staying up-to-date with the latest e-commerce trends, which is relevant but not explicitly stated as a required skill.

#### 4. Relevant Experience
- **E-commerce Specialist, XYZ Corporation (2018-Present):**
  - Managed multiple channels with significant reductions in stockouts and overstocking, indicating strong inventory management skills.
  - Developed and implemented SEO strategies for increased website traffic and improved search engine rankings, showcasing SEO expertise.
  - Executed online advertising campaigns with substantial increases in sales and conversion rates, demonstrating effective online advertising.
  - Analyzed website analytics to improve user experience and engagement, highlighting data analysis skills.
  - Collaborated with cross-functional teams for new product launches, promotions, and campaigns, indicating strong cross-functional collaboration.
- **E-commerce Coordinator, ABC Retail (2015-2018):**
  - Assisted in managing inventory levels, processing orders, and resolving customer inquiries, showing foundational experience in customer service.
  - Conducted keyword research and optimized product descriptions, indicating knowledge of SEO.
  - Assisted in creating and executing online advertising campaigns, resulting in significant sales increases.
  - Analyzed website analytics for trend identification and improvement, further emphasizing analytical skills.

#### 5. Education Alignment
- The candidate holds a Bachelor's Degree in Business Administration, which provides a solid foundation for understanding e-commerce principles and practices.
- The specific certifications mentioned (Google Analytics Certification, HubSpot Inbound Marketing Certification, Shopify Plus Certification) align with the job requirements and demonstrate the candidate's practical knowledge and skills.

#### 6. Recommendations
- **Machine Learning Knowledge:** The candidate should consider acquiring foundational knowledge or certifications in machine learning to better align with the job's focus.
- **E-commerce Trends:** The candidate should stay updated with the latest trends through continuous learning and networking.
- **Data-Driven Approach:** Reinforce their data-driven approach by focusing on continuous improvement projects and sharing success stories in data-driven solutions.
- **Cross-Functional Collaboration:** Emphasize their role in cross-functional teams and the positive outcomes from such collaborations to highlight their team collaboration skills.
- **Continued Learning:** Maintain and expand their skill set in analytics, e-commerce platforms, and customer service to stay competitive and relevant.

In [44]:
# Cell 39A — Save improved RAG analysis

print("Improved analysis length:", len(grounded_analysis), "characters")

# Store the final generated response
final_rag_analysis = grounded_analysis

print("\nFinal RAG analysis stored successfully.")

Improved analysis length: 4727 characters

Final RAG analysis stored successfully.

In [45]:
# Cell 40A — Check RAG response sections

expected_sections = [
    "Overall Match",
    "Matching Skills",
    "Missing or Not-Found Skills",
    "Relevant Experience",
    "Education Alignment",
    "Recommendations"
]

print("Checking expected sections:\n")

for section in expected_sections:
    found = section.lower() in final_rag_analysis.lower()
    print(f"{section}: {'Found' if found else 'Not found'}")

Checking expected sections:

Overall Match: Found
Matching Skills: Found
Missing or Not-Found Skills: Found
Relevant Experience: Found
Education Alignment: Found
Recommendations: Found

In [46]:
# Cell 41A — Create structured RAG output

structured_prompt = f"""
Convert the following resume-job analysis into valid JSON.

Return ONLY the JSON object.
Do not include markdown, explanations, or code fences.

Use exactly these keys:

{{
    "overall_match": "string",
    "matching_skills": ["skill 1", "skill 2"],
    "missing_or_not_found_skills": ["skill 1", "skill 2"],
    "relevant_experience": ["experience 1", "experience 2"],
    "education_alignment": "string",
    "recommendations": ["recommendation 1", "recommendation 2"]
}}

Do not add information that is not present in the analysis.

ANALYSIS:
{final_rag_analysis}
"""

print("Structured output prompt created.")
print("Prompt length:", len(structured_prompt), "characters")

Structured output prompt created.
Prompt length: 5274 characters

In [47]:
# Cell 42A — Generate structured JSON with Ollama

import requests

response = requests.post(
    "http://localhost:11434/api/generate",
    json={
        "model": "qwen2.5:3b",
        "prompt": structured_prompt,
        "stream": False,
        "format": "json"
    },
    timeout=180
)

response.raise_for_status()

structured_result = response.json()

structured_output_text = structured_result["response"]

print("Structured output generated successfully.")
print("\n" + structured_output_text)

Structured output generated successfully.

{
    "overall_match": "strong",
    "matching_skills": [
        "Inventory Management",
        "SEO for E-commerce",
        "Online Advertising",
        "Analytics",
        "Data Analysis",
        "E-commerce Platforms",
        "Customer Service"
    ],
    "missing_or_not_found_skills": [
        "Machine Learning",
        "Analytical"
    ],
    "relevant_experience": [
        "E-commerce Specialist, XYZ Corporation (2018-Present)",
        "E-commerce Coordinator, ABC Retail (2015-2018)"
    ],
    "education_alignment": "solid",
    "recommendations": [
        "Machine Learning Knowledge",
        "E-commerce Trends",
        "Data-Driven Approach",
        "Cross-Functional Collaboration",
        "Continued Learning"
    ]
}

In [48]:
# Cell 43A — Parse and validate structured JSON

import json

try:
    structured_output = json.loads(structured_output_text)

    print("Valid JSON: Yes")
    print("\nAvailable fields:")

    for key, value in structured_output.items():
        print(f"- {key}: {type(value).__name__}")

except json.JSONDecodeError as e:
    structured_output = None

    print("Valid JSON: No")
    print("JSON error:", e)

Valid JSON: Yes

Available fields:
- overall_match: str
- matching_skills: list
- missing_or_not_found_skills: list
- relevant_experience: list
- education_alignment: str
- recommendations: list

In [49]:
# Cell 44A — Inspect structured RAG output

print("=" * 70)
print("STRUCTURED RAG OUTPUT")
print("=" * 70)

print("\nOverall Match:")
print(structured_output["overall_match"])

print("\nMatching Skills:")
for skill in structured_output["matching_skills"]:
    print("-", skill)

print("\nMissing / Not-Found Skills:")
for skill in structured_output["missing_or_not_found_skills"]:
    print("-", skill)

print("\nRelevant Experience:")
for experience in structured_output["relevant_experience"]:
    print("-", experience)

print("\nEducation Alignment:")
print(structured_output["education_alignment"])

print("\nRecommendations:")
for recommendation in structured_output["recommendations"]:
    print("-", recommendation)

======================================================================
STRUCTURED RAG OUTPUT
======================================================================

Overall Match:
strong

Matching Skills:
- Inventory Management
- SEO for E-commerce
- Online Advertising
- Analytics
- Data Analysis
- E-commerce Platforms
- Customer Service

Missing / Not-Found Skills:
- Machine Learning
- Analytical

Relevant Experience:
- E-commerce Specialist, XYZ Corporation (2018-Present)
- E-commerce Coordinator, ABC Retail (2015-2018)

Education Alignment:
solid

Recommendations:
- Machine Learning Knowledge
- E-commerce Trends
- Data-Driven Approach
- Cross-Functional Collaboration
- Continued Learning

In [50]:
# Cell 45A — Compare structured RAG output with existing skill extraction

print("=" * 70)
print("EXISTING RULE-BASED SKILL EXTRACTION")
print("=" * 70)

row = analysis_df.iloc[0]

print("\nResume skills:")
print(row["resume_skills"])

print("\nJD skills:")
print(row["jd_skills"])

print("\nMatching skills:")
print(row["matching_skills"])

print("\nMissing skills:")
print(row["missing_skills"])

print("\nSkill score:")
print(row["skill_score"])

======================================================================
EXISTING RULE-BASED SKILL EXTRACTION
======================================================================

Resume skills:
['customer service', 'data analysis', 'e-commerce', 'excel', 'marketing', 'sales']

JD skills:
['e-commerce', 'machine learning']

Matching skills:
['e-commerce']

Missing skills:
['machine learning']

Skill score:
0.5

In [51]:
# Cell 46A — Combine deterministic matching with RAG analysis

final_result = {
    "hybrid_match_score": float(row["hybrid_score_100"]),
    "match_category": row["match_category"],
    "matching_skills": row["matching_skills"],
    "missing_skills": row["missing_skills"],
    "skill_score": float(row["skill_score"]) if pd.notna(row["skill_score"]) else None,
    "relevant_experience": structured_output["relevant_experience"],
    "education_alignment": structured_output["education_alignment"],
    "recommendations": structured_output["recommendations"]
}

print("Final combined result created successfully.")

print("\nHybrid Match Score:", final_result["hybrid_match_score"])
print("Match Category:", final_result["match_category"])
print("Matching Skills:", final_result["matching_skills"])
print("Missing Skills:", final_result["missing_skills"])
print("Skill Score:", final_result["skill_score"])

Final combined result created successfully.

Hybrid Match Score: 45.42016134915499
Match Category: Moderate
Matching Skills: ['e-commerce']
Missing Skills: ['machine learning']
Skill Score: 0.5

In [52]:
# Cell 47A — Display final combined result

print("=" * 70)
print("FINAL AI RESUME & JOB MATCHING RESULT")
print("=" * 70)

print(f"\nHybrid Match Score: {final_result['hybrid_match_score']:.2f}/100")
print(f"Match Category: {final_result['match_category']}")

print("\n" + "-" * 70)
print("MATCHING SKILLS")
print("-" * 70)

for skill in final_result["matching_skills"]:
    print(f"✓ {skill}")

print("\n" + "-" * 70)
print("MISSING SKILLS")
print("-" * 70)

for skill in final_result["missing_skills"]:
    print(f"• {skill}")

print("\n" + "-" * 70)
print("SKILL SCORE")
print("-" * 70)

print(f"{final_result['skill_score'] * 100:.1f}%")

print("\n" + "-" * 70)
print("RELEVANT EXPERIENCE")
print("-" * 70)

for experience in final_result["relevant_experience"]:
    print(f"• {experience}")

print("\n" + "-" * 70)
print("EDUCATION ALIGNMENT")
print("-" * 70)

print(final_result["education_alignment"])

print("\n" + "-" * 70)
print("RECOMMENDATIONS")
print("-" * 70)

for recommendation in final_result["recommendations"]:
    print(f"• {recommendation}")

======================================================================
FINAL AI RESUME & JOB MATCHING RESULT
======================================================================

Hybrid Match Score: 45.42/100
Match Category: Moderate

----------------------------------------------------------------------
MATCHING SKILLS
----------------------------------------------------------------------
✓ [
✓ '
✓ e
✓ -
✓ c
✓ o
✓ m
✓ m
✓ e
✓ r
✓ c
✓ e
✓ '
✓ ]

----------------------------------------------------------------------
MISSING SKILLS
----------------------------------------------------------------------
• [
• '
• m
• a
• c
• h
• i
• n
• e
•
• l
• e
• a
• r
• n
• i
• n
• g
• '
• ]

----------------------------------------------------------------------
SKILL SCORE
----------------------------------------------------------------------
50.0%

----------------------------------------------------------------------
RELEVANT EXPERIENCE
----------------------------------------------------------------------
• E-commerce Specialist, XYZ Corporation (2018-Present)
• E-commerce Coordinator, ABC Retail (2015-2018)

----------------------------------------------------------------------
EDUCATION ALIGNMENT
----------------------------------------------------------------------
solid

----------------------------------------------------------------------
RECOMMENDATIONS
----------------------------------------------------------------------
• Machine Learning Knowledge
• E-commerce Trends
• Data-Driven Approach
• Cross-Functional Collaboration
• Continued Learning

In [53]:
# Cell 48A — Check final result data types

print("Matching skills type:",
      type(final_result["matching_skills"]))

print("Missing skills type:",
      type(final_result["missing_skills"]))

print("Relevant experience type:",
      type(final_result["relevant_experience"]))

print("\nMatching skills value:")
print(final_result["matching_skills"])

print("\nMissing skills value:")
print(final_result["missing_skills"])

Matching skills type: <class 'str'>
Missing skills type: <class 'str'>
Relevant experience type: <class 'list'>

Matching skills value:
['e-commerce']

Missing skills value:
['machine learning']

In [54]:
# Cell 48B — Convert skill fields back to proper Python lists

import ast

def ensure_list(value):
    """Convert a list-like string into a Python list."""
    
    if isinstance(value, list):
        return value
    
    if isinstance(value, str):
        try:
            parsed = ast.literal_eval(value)
            
            if isinstance(parsed, list):
                return parsed
            
        except (ValueError, SyntaxError):
            pass
        
        # Fallback: treat the string as one item
        return [value]
    
    return [value]


# Fix the fields
final_result["matching_skills"] = ensure_list(
    final_result["matching_skills"]
)

final_result["missing_skills"] = ensure_list(
    final_result["missing_skills"]
)

final_result["relevant_experience"] = ensure_list(
    final_result["relevant_experience"]
)


# Verify
print("Matching skills type:",
      type(final_result["matching_skills"]))

print("Missing skills type:",
      type(final_result["missing_skills"]))

print("Relevant experience type:",
      type(final_result["relevant_experience"]))

print("\nMatching skills:")
print(final_result["matching_skills"])

print("\nMissing skills:")
print(final_result["missing_skills"])

Matching skills type: <class 'list'>
Missing skills type: <class 'list'>
Relevant experience type: <class 'list'>

Matching skills:
['e-commerce']

Missing skills:
['machine learning']

In [55]:
# Cell 49A — Save corrected final result

import json
from pathlib import Path

results_dir = Path("../results")
results_dir.mkdir(parents=True, exist_ok=True)

output_path = results_dir / "rag_demo_output.json"

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(final_result, f, indent=4, ensure_ascii=False)

print("Final result saved successfully.")
print("Saved to:", output_path.resolve())

Final result saved successfully.
Saved to: C:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\results\rag_demo_output.json

In [56]:
# Cell 50A — Define structured output schema with Pydantic

from pydantic import BaseModel, Field
from typing import List


class ResumeMatchResult(BaseModel):
    matching_skills: List[str] = Field(
        description="Skills explicitly found in both the resume and job description."
    )

    missing_skills: List[str] = Field(
        description="Skills explicitly required by the job description but not found in the resume."
    )

    relevant_experience: List[str] = Field(
        description="Relevant experience explicitly supported by the resume."
    )

    education_alignment: str = Field(
        description="Explanation of how the resume education aligns with the job description."
    )

    recommendations: List[str] = Field(
        description="Evidence-based recommendations based on identified gaps."
    )


print("Pydantic schema created successfully.")
print(ResumeMatchResult.model_json_schema())

Pydantic schema created successfully.
{'properties': {'matching_skills': {'description': 'Skills explicitly found in both the resume and job description.', 'items': {'type': 'string'}, 'title': 'Matching Skills', 'type': 'array'}, 'missing_skills': {'description': 'Skills explicitly required by the job description but not found in the resume.', 'items': {'type': 'string'}, 'title': 'Missing Skills', 'type': 'array'}, 'relevant_experience': {'description': 'Relevant experience explicitly supported by the resume.', 'items': {'type': 'string'}, 'title': 'Relevant Experience', 'type': 'array'}, 'education_alignment': {'description': 'Explanation of how the resume education aligns with the job description.', 'title': 'Education Alignment', 'type': 'string'}, 'recommendations': {'description': 'Evidence-based recommendations based on identified gaps.', 'items': {'type': 'string'}, 'title': 'Recommendations', 'type': 'array'}}, 'required': ['matching_skills', 'missing_skills', 'relevant_experience', 'education_alignment', 'recommendations'], 'title': 'ResumeMatchResult', 'type': 'object'}

In [57]:
# Cell 51A — Validate LLM output using Pydantic

validated_result = ResumeMatchResult(
    matching_skills=final_result["matching_skills"],
    missing_skills=final_result["missing_skills"],
    relevant_experience=final_result["relevant_experience"],
    education_alignment=final_result["education_alignment"],
    recommendations=final_result["recommendations"]
)

print("Pydantic validation successful!")
print("\nValidated result:")
print(validated_result.model_dump())

Pydantic validation successful!

Validated result:
{'matching_skills': ['e-commerce'], 'missing_skills': ['machine learning'], 'relevant_experience': ['E-commerce Specialist, XYZ Corporation (2018-Present)', 'E-commerce Coordinator, ABC Retail (2015-2018)'], 'education_alignment': 'solid', 'recommendations': ['Machine Learning Knowledge', 'E-commerce Trends', 'Data-Driven Approach', 'Cross-Functional Collaboration', 'Continued Learning']}

In [58]:
# Cell 52A — Save Pydantic-validated result

validated_output_path = results_dir / "validated_rag_output.json"

with open(validated_output_path, "w", encoding="utf-8") as f:
    json.dump(
        validated_result.model_dump(),
        f,
        indent=4,
        ensure_ascii=False
    )

print("Validated result saved successfully.")
print("Saved to:", validated_output_path.resolve())

Validated result saved successfully.
Saved to: C:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\results\validated_rag_output.json

In [59]:
# Cell 53A — Final GenAI/RAG pipeline summary

print("=" * 70)
print("GENAI + RAG PIPELINE — FINAL SUMMARY")
print("=" * 70)

print("\n1. DOCUMENT INPUT")
print("   ✓ Resume")
print("   ✓ Job Description")

print("\n2. RETRIEVAL")
print(f"   ✓ Resume chunks: {len(resume_chunks)}")
print(f"   ✓ Embedding dimension: {resume_embeddings.shape[1]}")
print(f"   ✓ FAISS index size: {resume_index.ntotal}")

print("\n3. DETERMINISTIC MATCHING")
print(f"   ✓ Hybrid match score: {final_result['hybrid_match_score']:.2f}/100")
print(f"   ✓ Match category: {final_result['match_category']}")
print(f"   ✓ Matching skills: {final_result['matching_skills']}")
print(f"   ✓ Missing skills: {final_result['missing_skills']}")
print(f"   ✓ Skill score: {final_result['skill_score'] * 100:.1f}%")

print("\n4. GENERATIVE AI")
print("   ✓ Local model: qwen2.5:3b")
print("   ✓ Grounded RAG analysis generated")
print("   ✓ Structured JSON generated")

print("\n5. OUTPUT VALIDATION")
print("   ✓ Pydantic validation successful")

print("\n6. SAVED OUTPUTS")
print("   ✓ rag_demo_output.json")
print("   ✓ validated_rag_output.json")

print("\n" + "=" * 70)
print("GENAI + RAG PIPELINE COMPLETED SUCCESSFULLY")
print("=" * 70)

======================================================================
GENAI + RAG PIPELINE — FINAL SUMMARY
======================================================================

1. DOCUMENT INPUT
   ✓ Resume
   ✓ Job Description

2. RETRIEVAL
   ✓ Resume chunks: 3
   ✓ Embedding dimension: 384
   ✓ FAISS index size: 3

3. DETERMINISTIC MATCHING
   ✓ Hybrid match score: 45.42/100
   ✓ Match category: Moderate
   ✓ Matching skills: ['e-commerce']
   ✓ Missing skills: ['machine learning']
   ✓ Skill score: 50.0%

4. GENERATIVE AI
   ✓ Local model: qwen2.5:3b
   ✓ Grounded RAG analysis generated
   ✓ Structured JSON generated

5. OUTPUT VALIDATION
   ✓ Pydantic validation successful

6. SAVED OUTPUTS
   ✓ rag_demo_output.json
   ✓ validated_rag_output.json

======================================================================
GENAI + RAG PIPELINE COMPLETED SUCCESSFULLY
======================================================================

In [14]:
# Cell 33 — Create embeddings for resume and JD chunks

from sentence_transformers import SentenceTransformer
import numpy as np

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

resume_embeddings = embedding_model.encode(
    resume_chunks,
    convert_to_numpy=True,
    normalize_embeddings=True
)

jd_embeddings = embedding_model.encode(
    jd_chunks,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Resume embeddings shape:", resume_embeddings.shape)
print("JD embeddings shape:", jd_embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Me\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

c:\Users\Me\OneDrive\Desktop\Resume project ( Gen AI-RAG)\.venv\Lib\site-packages\huggingface_hub\file_download.py:150: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Me\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Resume embeddings shape: (7, 384)
JD embeddings shape: (1, 384)

In [15]:
# Cell 34 — Create FAISS index for resume chunks

import faiss
import numpy as np

# Number of dimensions in our embeddings
embedding_dimension = resume_embeddings.shape[1]

# Create FAISS index using inner product
# Because our embeddings are normalized, inner product = cosine similarity
resume_index = faiss.IndexFlatIP(embedding_dimension)

# Add resume chunk embeddings to the index
resume_index.add(resume_embeddings.astype("float32"))

print("FAISS index created successfully.")
print("Embedding dimension:", embedding_dimension)
print("Number of resume chunks in index:", resume_index.ntotal)

FAISS index created successfully.
Embedding dimension: 384
Number of resume chunks in index: 7

In [16]:
# Cell 35 — Retrieve the most relevant resume chunks

# Number of chunks to retrieve
top_k = min(3, len(resume_chunks))

# Search FAISS using the job description embedding
similarities, indices = resume_index.search(
    jd_embeddings.astype("float32"),
    top_k
)

print("Top matching resume chunks:\n")

for rank, (score, index) in enumerate(
    zip(similarities[0], indices[0]), start=1
):
    print(f"Rank {rank}")
    print(f"Similarity score: {score:.4f}")
    print(f"Resume chunk index: {index}")
    print(f"Text: {resume_chunks[index]}")
    print("-" * 80)

Top matching resume chunks:

Rank 1
Similarity score: 0.5350
Resume chunk index: 5
Text: atforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "Innovator of the Year" award for developing and implementing a data-driven approach to inventory management * Featured speaker at the "E-commerce Summit" conference, presenting on "Optimizing Inventory Levels for E-commerce Success" * Developed and implemented a social media strategy that increased followers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot I
--------------------------------------------------------------------------------
Rank 2
Similarity score: 0.5291
Resume chunk index: 1
Text: ne sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies. Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strate
--------------------------------------------------------------------------------
Rank 3
Similarity score: 0.5062
Resume chunk index: 3
Text: ve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytic
--------------------------------------------------------------------------------

In [17]:
# Cell 36 — Build retrieved context

retrieved_chunks = []

for index in indices[0]:
    retrieved_chunks.append(resume_chunks[index])

retrieved_context = "\n\n".join(retrieved_chunks)

print("Retrieved context created successfully.")
print("\nNumber of retrieved chunks:", len(retrieved_chunks))

print("\nRetrieved context:\n")
print(retrieved_context)

Retrieved context created successfully.

Number of retrieved chunks: 3

Retrieved context:

atforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "Innovator of the Year" award for developing and implementing a data-driven approach to inventory management * Featured speaker at the "E-commerce Summit" conference, presenting on "Optimizing Inventory Levels for E-commerce Success" * Developed and implemented a social media strategy that increased followers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot I

ne sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies. Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strate

ve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytic

In [19]:
# Cell 37 — Check available JD variables

jd_variables = [
    name for name in globals()
    if "jd" in name.lower() or "job" in name.lower()
]

print("Available JD/job-related variables:")
for name in jd_variables:
    print("-", name)

Available JD/job-related variables:
- jd_text
- jd_chunks
- jd_embeddings

In [21]:
# Cell 37 — Prepare RAG context

rag_context = f"""
JOB DESCRIPTION:
{jd_text}

RELEVANT RESUME INFORMATION:
{retrieved_context}
"""

print("RAG context prepared successfully.")
print("\n" + rag_context)

RAG context prepared successfully.


JOB DESCRIPTION:
Be part of a passionate team at the forefront of machine learning as a E-commerce Specialist, delivering solutions that shape the future.

RELEVANT RESUME INFORMATION:
atforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "Innovator of the Year" award for developing and implementing a data-driven approach to inventory management * Featured speaker at the "E-commerce Summit" conference, presenting on "Optimizing Inventory Levels for E-commerce Success" * Developed and implemented a social media strategy that increased followers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot I

ne sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies. Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strate

ve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytic

In [22]:
# Cell 38 — Validate RAG context

print("RAG context length:", len(rag_context), "characters")

if len(rag_context.strip()) > 0:
    print("RAG context is ready for the LLM.")
else:
    print("WARNING: RAG context is empty.")

RAG context length: 1691 characters
RAG context is ready for the LLM.

In [23]:
# Cell 39 — Create RAG prompt

rag_prompt = f"""
You are an AI Resume and Job Matching Assistant.

Analyze the candidate's resume information against the job description.

Use ONLY the information provided in the context below.
Do not invent skills, qualifications, experience, or achievements.

JOB DESCRIPTION AND RETRIEVED RESUME CONTEXT:
{rag_context}

Provide the analysis in the following format:

1. Overall Match
2. Matching Skills
3. Missing or Weak Skills
4. Relevant Experience
5. Education Alignment
6. Recommendations for the Candidate

Keep the analysis factual and concise.
"""

print("RAG prompt created successfully.")
print("Prompt length:", len(rag_prompt), "characters")

RAG prompt created successfully.
Prompt length: 2219 characters

In [24]:
# Cell 40 — Generate AI analysis using local Ollama model

import requests

response = requests.post(
    "http://localhost:11434/api/generate",
    json={
        "model": "qwen2.5:3b",
        "prompt": rag_prompt,
        "stream": False
    },
    timeout=180
)

response.raise_for_status()

ollama_result = response.json()

ai_analysis = ollama_result["response"]

print("AI analysis generated successfully.")
print("\n" + ai_analysis)

AI analysis generated successfully.

### Analysis

#### 1. Overall Match
The candidate's experience and skills closely align with the job description of an E-commerce Specialist at the forefront of machine learning, especially with their expertise in data-driven inventory management, social media marketing, and cross-functional collaboration. The candidate's achievements in inventory management, SEO optimization, and cross-functional teamwork demonstrate the ability to contribute effectively to an innovative and forward-thinking team.

#### 2. Matching Skills
- Data-Driven Approach: The candidate has developed and implemented a data-driven approach to inventory management, which is highly relevant.
- Inventory Management: Successful management of inventory levels resulting in reduced stockouts and overstocking.
- SEO and Content Optimization: Expertise in SEO and optimizing product descriptions to improve search engine rankings.
- Cross-Functional Collaboration: Demonstrated ability to collaborate with cross-functional teams to launch new product lines and promotions.
- Social Media Marketing: Experience in developing and implementing a social media strategy that increased followers and engagement significantly.
- Machine Learning: Although not explicitly mentioned, the candidate's data-driven approach and optimization skills suggest familiarity with machine learning principles.

#### 3. Missing or Weak Skills
- Machine Learning: While the candidate has strong analytical and data-driven skills, specific knowledge in machine learning algorithms and applications is not highlighted.
- Direct Experience with Machine Learning: The candidate’s experience is more focused on inventory management, customer engagement, and optimization strategies rather than direct machine learning application.
- Technical Coding: The candidate does not have direct technical coding experience, which could be a critical component for a machine learning-focused role.

#### 4. Relevant Experience
- Managed inventory levels across multiple channels, resulting in significant reductions in stockouts and overstocking.
- Developed and implemented an SEO strategy resulting in a significant increase in sales.
- Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns.
- Developed and implemented a social media strategy that achieved significant increases in followers and engagement.
- Analyzed website analytics to improve customer engagement.

#### 5. Education Alignment
- While specific education details are not provided, certifications like Google Analytics Certification and HubSpot I are relevant to the job. The candidate has a strong foundation in data analysis and e-commerce operations.

#### 6. Recommendations for the Candidate
- The candidate should consider seeking additional certifications in machine learning and programming languages such as Python or R to strengthen their technical background.
- Engaging in open-source projects or contributing to GitHub repositories related to machine learning could help demonstrate hands-on experience and learning.
- Attending conferences or workshops focused on machine learning and e-commerce can provide valuable networking and learning opportunities.
- Highlighting specific machine learning-related achievements or projects in their resume, if applicable, to further align with the role.

In [25]:
# Cell 41 — Save and inspect the complete AI analysis

print("AI analysis length:", len(ai_analysis), "characters")

print("\n" + "=" * 80)
print("COMPLETE AI ANALYSIS")
print("=" * 80)

print(ai_analysis)

AI analysis length: 3369 characters

================================================================================
COMPLETE AI ANALYSIS
================================================================================
### Analysis

#### 1. Overall Match
The candidate's experience and skills closely align with the job description of an E-commerce Specialist at the forefront of machine learning, especially with their expertise in data-driven inventory management, social media marketing, and cross-functional collaboration. The candidate's achievements in inventory management, SEO optimization, and cross-functional teamwork demonstrate the ability to contribute effectively to an innovative and forward-thinking team.

#### 2. Matching Skills
- Data-Driven Approach: The candidate has developed and implemented a data-driven approach to inventory management, which is highly relevant.
- Inventory Management: Successful management of inventory levels resulting in reduced stockouts and overstocking.
- SEO and Content Optimization: Expertise in SEO and optimizing product descriptions to improve search engine rankings.
- Cross-Functional Collaboration: Demonstrated ability to collaborate with cross-functional teams to launch new product lines and promotions.
- Social Media Marketing: Experience in developing and implementing a social media strategy that increased followers and engagement significantly.
- Machine Learning: Although not explicitly mentioned, the candidate's data-driven approach and optimization skills suggest familiarity with machine learning principles.

#### 3. Missing or Weak Skills
- Machine Learning: While the candidate has strong analytical and data-driven skills, specific knowledge in machine learning algorithms and applications is not highlighted.
- Direct Experience with Machine Learning: The candidate’s experience is more focused on inventory management, customer engagement, and optimization strategies rather than direct machine learning application.
- Technical Coding: The candidate does not have direct technical coding experience, which could be a critical component for a machine learning-focused role.

#### 4. Relevant Experience
- Managed inventory levels across multiple channels, resulting in significant reductions in stockouts and overstocking.
- Developed and implemented an SEO strategy resulting in a significant increase in sales.
- Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns.
- Developed and implemented a social media strategy that achieved significant increases in followers and engagement.
- Analyzed website analytics to improve customer engagement.

#### 5. Education Alignment
- While specific education details are not provided, certifications like Google Analytics Certification and HubSpot I are relevant to the job. The candidate has a strong foundation in data analysis and e-commerce operations.

#### 6. Recommendations for the Candidate
- The candidate should consider seeking additional certifications in machine learning and programming languages such as Python or R to strengthen their technical background.
- Engaging in open-source projects or contributing to GitHub repositories related to machine learning could help demonstrate hands-on experience and learning.
- Attending conferences or workshops focused on machine learning and e-commerce can provide valuable networking and learning opportunities.
- Highlighting specific machine learning-related achievements or projects in their resume, if applicable, to further align with the role.

In [26]:
# Cell 42 — Create a stricter grounded RAG prompt

grounded_rag_prompt = f"""
You are an AI Resume and Job Matching Assistant.

Your task is to compare the job description with the retrieved resume information.

IMPORTANT RULES:
1. Use ONLY information explicitly present in the provided context.
2. Do NOT infer or assume that the candidate has a skill, qualification,
   technology, experience, or achievement unless it is explicitly stated.
3. If a skill or qualification is not mentioned in the resume context,
   describe it as "Not found in the retrieved resume information".
4. Do NOT treat general abilities such as "data-driven", "optimization",
   or "analytical" as evidence of machine learning, programming, or any
   other specific technical skill unless explicitly stated.
5. Distinguish between:
   - explicitly demonstrated skills
   - missing/not-found requirements
   - general transferable experience
6. Do not invent employers, job titles, technologies, projects,
   qualifications, years of experience, or achievements.
7. Keep the analysis factual and evidence-based.

JOB DESCRIPTION:
{jd_text}

RETRIEVED RESUME INFORMATION:
{retrieved_context}

Provide the analysis using exactly these sections:

1. Overall Match
2. Matching Skills
3. Missing or Not-Found Skills
4. Relevant Experience
5. Education Alignment
6. Recommendations

For recommendations, only suggest improvements based on gaps identified
from the job description and retrieved resume information.
"""

print("Grounded RAG prompt created successfully.")
print("Prompt length:", len(grounded_rag_prompt), "characters")

Grounded RAG prompt created successfully.
Prompt length: 3022 characters

In [27]:
# Cell 43 — Generate grounded AI analysis

import requests

response = requests.post(
    "http://localhost:11434/api/generate",
    json={
        "model": "qwen2.5:3b",
        "prompt": grounded_rag_prompt,
        "stream": False
    },
    timeout=180
)

response.raise_for_status()

grounded_result = response.json()

grounded_analysis = grounded_result["response"]

print("Grounded AI analysis generated successfully.")
print("\n" + grounded_analysis)

Grounded AI analysis generated successfully.

### Analysis

#### 1. Overall Match
The resume information provided aligns well with the job description. The candidate has experience in e-commerce, machine learning applications, and customer service achievements, which are key components of the role. However, the specific mention of machine learning applications is not found in the retrieved information.

#### 2. Matching Skills
- **Customer Service Achievements:** The candidate's achievements in managing inventory levels, developing and implementing social media strategies, and presenting at conferences align with the job responsibilities of a E-commerce Specialist.
- **Machine Learning Applications:** Not found in the retrieved resume information.
- **Analytics and Data-Driven Decisions:** The candidate's experience in analyzing complex data sets and making data-driven decisions is relevant to the role.
- **E-commerce Expertise:** The candidate's experience in managing inventory levels and developing and implementing strategies aligns with the job responsibilities.
- **Machine Learning:** Not found in the retrieved resume information.

#### 3. Missing or Not-Found Skills
- **Machine Learning:** Not found in the retrieved resume information.
- **Programming and Technical Skills:** The candidate's experience in customer service and e-commerce does not explicitly demonstrate programming or technical skills related to machine learning.

#### 4. Relevant Experience
- **E-commerce Specialist, XYZ Corporation (2018-Present):**
  - Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking.
  - Developed and implemented SEO strategies, resulting in a 20% increase in sales.
  - Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns.
- **E-commerce Coordinator, ABC Retail (2015-2018):**
  - Assisted in managing inventory levels, processing orders, and resolving customer inquiries.
  - Conducted keyword research and optimized product descriptions to improve search engine rankings.
  - Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales.
  - Analyzed website analytics.

#### 5. Education Alignment
- **Google Analytics Certification:** The candidate has a certification that aligns with the role.
- **HubSpot I:** The candidate's experience in e-commerce and customer service does not directly align with the HubSpot certification, which is specific to digital marketing and sales.

#### 6. Recommendations
- **Machine Learning and Programming:** Given the job responsibilities and the lack of specific machine learning experience, it would be beneficial for the candidate to gain certifications or relevant experience in machine learning or programming. This could include taking online courses or pursuing certifications such as Google's Machine Learning Professional Certificate.
- **Technical Skills:** To enhance their technical skills, the candidate could consider learning Python, data analysis tools, and cloud computing platforms, which are common in machine learning and e-commerce roles.
- **Specific Projects:** The candidate could identify specific projects or case studies that demonstrate their ability to apply machine learning or programming to solve complex problems in e-commerce. This could include analyzing data sets, developing predictive models, or implementing automation tools.
- **Continued Professional Development:** Keeping up-to-date with the latest e-commerce trends and technologies would be beneficial, as indicated by the candidate's experience and achievements in this area.
- **Programming Languages:** Since the job description does not explicitly mention programming, it would be helpful for the candidate to learn and demonstrate proficiency in at least one programming language commonly used in machine learning and e-commerce, such as Python or R.

In [28]:
# Cell 44 — Inspect retrieved evidence

print("=" * 80)
print("RETRIEVED RESUME EVIDENCE")
print("=" * 80)

print(retrieved_context)

print("\n" + "=" * 80)
print("END OF RETRIEVED EVIDENCE")
print("=" * 80)

================================================================================
RETRIEVED RESUME EVIDENCE
================================================================================
atforms (Shopify, WooCommerce) * Customer Service Achievements: * Winner of the XYZ Corporation's "Innovator of the Year" award for developing and implementing a data-driven approach to inventory management * Featured speaker at the "E-commerce Summit" conference, presenting on "Optimizing Inventory Levels for E-commerce Success" * Developed and implemented a social media strategy that increased followers by 500% and engagement by 200% Certifications: * Google Analytics Certification * HubSpot I

ne sales, improving website traffic, and optimizing inventory levels. Skilled in analyzing complex data sets, identifying trends, and making data-driven decisions. Passionate about staying up-to-date with the latest e-commerce trends and technologies. Professional Experience: E-commerce Specialist, XYZ Corporation (2018-Present) * Managed inventory levels across multiple channels, resulting in a 25% reduction in stockouts and a 15% reduction in overstocking * Developed and implemented SEO strate

ve customer engagement * Collaborated with cross-functional teams to launch new product lines, promotions, and marketing campaigns E-commerce Coordinator, ABC Retail (2015-2018) * Assisted in managing inventory levels, processing orders, and resolving customer inquiries * Conducted keyword research and optimized product descriptions to improve search engine rankings * Assisted in creating and executing online advertising campaigns, resulting in a 20% increase in sales * Analyzed website analytic

================================================================================
END OF RETRIEVED EVIDENCE
================================================================================